api_platform:
    resource: .
    type: api_platform
    prefix: /api

    format:
#        json

#        json: [ 'application/json' ]
#
#        jsonld: [ 'application/ld+json' ]
#
#        html: [ 'text/html' ]
#
#        xml: [ 'application/xml', 'text/xml' ]
#
#        yaml: [ 'application/x-yaml' ]
#
#        csv: [ 'text/csv' ]
