api_platform:
    resource: .
    type: api_platform
    prefix: /api

#    formats:
#        json:
#            mime_types: [ 'application/json' ]
#
#        jsonld:
#            mime_types: [ 'application/ld+json' ]
#
#        html:
#            mime_types: [ 'text/html' ]
#
#        xml:
#            mime_types: [ 'application/xml', 'text/xml' ]
#
#        yaml:
#            mime_types: [ 'application/x-yaml' ]
#
#        csv:
#            mime_types: [ 'text/csv' ]
